---
- hosts: all
  tasks:
  - name: Install tools
    become: true
    yum: 
      name: "{{ item }}"
      state: installed
    loop: '{{ install_common_packages }}'
  - name: Template file for welcome_message
    become: true
    ansible.builtin.template:
      src: welcome_message.j2
      dest: /etc/profile.d/welcome_message.sh
      owner: root 
      mode: '0644' 

- hosts: db
  tasks:
  - name: Install MYSQL database
    yum:
      name:
        - mariadb.x86_64
      state: removed

- hosts: web
  tasks:
  - name: Start service lxc, if not started
    become: true
    ansible.builtin.service:
      name: lxc
      state: started
  - name: Enable service snapd, if not enabled
    become: true
    ansible.builtin.service:
      name: snapd
      state: started 
  
  - name: Add the user 'kafka' with a specific uid and a primary group of 'wheel'
    become: true
    ansible.builtin.user:
      name: kafka
#      password: 'kafka'
      comment: Create Kafka user
#      uid: 1040
      group: wheel
      state: present
      shell: /bin/bash       # Defaults to /bin/bash
      system: no             # Defaults to no
      create_home: yes        # Defaults to yes
      home: /home/kafka  # Defaults to /home/<username>
      
  - name: Create Download directory if it does not exist
    become: true
    ansible.builtin.file:
      path: /home/kafka/Downloads
      state: directory
#      mode: '0755'
  - name: Downloading and Extracting the Kafka Binaries (Download kafka_2.12-2.7.1.tgz)
    become: true
    get_url:
      url: https://downloads.apache.org/kafka/2.7.1/kafka_2.12-2.7.1.tgz
      dest: /home/kafka/Downloads/kafka.tgz
      mode: '0777'

  - name: Unarchive kafka_2.12-2.7.1.tgz that is already on the remote machine
    become: true
    ansible.builtin.unarchive:
      src: /home/kafka/Downloads/kafka.tgz
      dest: /home/kafka/
      remote_src: yes
      mode: '0777'


  - name: Run command to rename folder.
    become: true
    command: mv /home/kafka/kafka_2.12-2.7.1 /home/kafka/kafka 
    args:
      chdir: /home/kafka/
      creates: /home/kafka/kafka

   
#  - name:  Create directories
#    become: true
#    file:
#      path: "{{ item }}"
#      state: directory
#    with_items: '{{ node_directories_to_create }}'
#      mode: '0755'
##  - name: Template file for Configuring the Kafka Server
##    become: true
##    ansible.builtin.template:
##      src: server.properties.j2
##      dest: /home/kafka/config/server.properties
##      owner: kafka 
##      mode: '0644'
  - name: Template file for Creating Systemd Unit Files and Starting the zookeeper Server
    become: true
    ansible.builtin.template:
      src: zookeeper.service.j2
      dest: /etc/systemd/system/zookeeper.service
      owner: root
  - name: Template file for Creating Systemd Unit Files and Starting the Kafka Server
    become: true
    ansible.builtin.template:
      src: kafka.service.j2
      dest: /etc/systemd/system/kafka.service    
      owner: root

  - name: Enable and Start Kafka service, if not enabled
    become: true
    ansible.builtin.service:
      name: kafka
      state: reloaded

  - name: Enable and Start Kafka service, if not enabled
    become: true
    ansible.builtin.service:
      name: kafka
      state: started

