---
- hosts: all
  tasks:
  - name: Install tools
    become: true
    yum: 
      name: "{{ item }}"
      state: installed
    with_items: '{{ install_common_packages }}'
  - name: Template
    become: true
    template:
      src: welcome_message.j2
      dest: /etc/profile.d/welcome_message.sh
      owner: root 
      mode: '0644'
  - name: Create Download directory if it does not exist
    become: true
    file:
      path: /home/kafka/Downloads
      state: directory
#      mode: '0755'
  - name: Downloading and Extracting the Kafka Binaries (Download kafka_2.12-2.7.1.tgz)
    become: true
    get_url:
      url: https://downloads.apache.org/kafka/2.7.1/kafka_2.12-2.7.1.tgz
      dest: /home/kafka/Downloads/kafka.tgz
      mode: '0777'
  
  - name: Unarchive kafka_2.12-2.7.1.tgz that is already on the remote machine
    become: true
    unarchive:
      src: /home/kafka/Downloads/kafka.tgz 
      dest: /home/kafka/
      remote_src: yes
      mode: '0777'


  - name: Run command to rename folder.
    become: true
    command: mv /home/kafka/kafka_2.12-2.7.1 /home/kafka/kafka 
    args:
      chdir: /home/kafka/
      creates: /home/kafka/kafka

  - name: Template file for Creating Systemd Unit Files and Starting the zookeeper Server
    become: true
    ansible.builtin.template:
      src: zookeeper.service.j2
      dest: /etc/systemd/system/zookeeper.service
      owner: root
      mode: '0777'

  - name: Template file for Creating Systemd Unit Files and Starting the Kafka Server
    become: true
    ansible.builtin.template:
      src: kafka.service.j2
      dest: /etc/systemd/system/kafka.service    
      owner: root
      mode: '0777'

  - name: Template file for Creating kafka-server-start.sh  Files and Starting the Kafka Server
    become: true
    ansible.builtin.template:
      src: kafka-server-start.j2
      dest: /home/kafka/kafka/bin/kafka-server-start.sh
      owner: root
      mode: '0777'

- hosts: zookeeper
  tasks:

  - name: Enable and Start zookeeper service, if not enabled
    become: true
    ansible.builtin.service:
      name: zookeeper
      enabled: yes

  - name: Enable and Start zookeeper service, if not enabled
    become: true
    ansible.builtin.service:
      name: zookeeper
      state: started

- hosts: broker
  tasks:
  
  - name: Enable and Start Kafka service, if not enabled
    become: true
    ansible.builtin.service:
      name: kafka
      enabled: yes

  - name: Enable and Start Kafka service, if not enabled
    become: true
    ansible.builtin.service:
      name: kafka
      state: started

