---
- hosts: all
  tasks:
  - name: Create directories
    file:
      path: "{{ item }}"
      state: directory
    with_items: '{{ node_directories_to_create }}'
    #    mode: '0755'
  - name: Template file for welcome_message
    become: true
    ansible.builtin.template:
      src: welcome_message.j2
      dest: /etc/profile.d/welcome_message.sh
      owner: root 
      mode: '0644'
  - name: Create configuration file for apps
    ansible.builtin.template:
      src: config.properties.j2
      dest: /home/ec2-user/config/config.properties
      mode: '0644'

- hosts: webserver
  become: true
  gather_facts: no
  tasks:
  - name: Update repos
    yum:
      name: "*"
      state: latest
  - name: Install latest Java JDK and Git
    yum:
      name: "{{ item }}"
      state: installed
    loop: '{{ packages_to_install }}'
#  - name: Setting default java
#    alternatives:
#      name: java
#      link: /usr/bin/java
#      path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.amzn2.0.1.x86_64/jre/bin/java
 
- hosts: apps 
  become: true
  gather_facts: no
  tasks:
  - name: Install Node from the EPEL Repository
    shell: |
      curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
  - name: Install Node JS
    yum:
      name: nodejs
      state: installed
  - name: Install latest Java JDK and Git
    yum:
      name: "{{ item }}"
      state: installed
    loop: '{{ packages_to_install }}'
